g the-hive-admin -
g the-hive-agent-api -
g the-hive-agent-state -
u the-hive-admin - "The Hive administration daemon" /var/empty
u the-hive-agent-api - "The Hive agent API" /var/empty
m the-hive-admin the-hive-agent-state
m the-hive-agent-api the-hive-agent-state
